# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pastagrammer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pastagrammer
	pod 'AlamofireImage'
  	pod 'Parse'
  	pod 'MessageInputBar'

  target 'PastagrammerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PastagrammerUITests' do
    # Pods for testing
  end

end
